INSERT INTO farmers (id, name) VALUES ('f001', 'พี่ปู');
INSERT INTO farmers (id, name) VALUES ('f002', 'น้านุ้ย');
INSERT INTO farmers (id, name) VALUES ('f003', 'พี่แบงค์');
INSERT INTO farmers (id, name) VALUES ('f004', 'พ่อ หมู');
INSERT INTO farmers (id, name) VALUES ('f005', 'พ่อ');
INSERT INTO farmers (id, name) VALUES ('f006', 'น้าต้อย');
INSERT INTO farmers (id, name) VALUES ('f007', 'ป้าผิว/พี่ตุ๊ก');
INSERT INTO farmers (id, name) VALUES ('f008', 'ป้าผิว 2');
INSERT INTO farmers (id, name) VALUES ('f009', 'น้ารุณ');
INSERT INTO farmers (id, name) VALUES ('f010', 'พี่แจ็ค ตาคม');
INSERT INTO farmers (id, name) VALUES ('f011', 'ตาคม');
INSERT INTO farmers (id, name) VALUES ('f012', 'ตาคม2');
INSERT INTO farmers (id, name) VALUES ('f013', 'ป้าเพ็ญ / ลุงชาติ');
INSERT INTO farmers (id, name) VALUES ('f014', 'เป็ดน้อย');
INSERT INTO farmers (id, name) VALUES ('f015', 'โกนุ้ย/โบ้');
INSERT INTO farmers (id, name) VALUES ('f016', 'น้าสวย');
INSERT INTO farmers (id, name) VALUES ('f017', 'น้าดำ');
INSERT INTO farmers (id, name) VALUES ('f018', 'น้าหลวงสมคิด');
INSERT INTO farmers (id, name) VALUES ('f019', 'กลุ่ม');
INSERT INTO farmers (id, name) VALUES ('f020', 'พี่จุ้ม/น้าน้อย');
INSERT INTO farmers (id, name) VALUES ('f021', 'น้าชบา');
INSERT INTO farmers (id, name) VALUES ('f022', 'น้าชบา2');
INSERT INTO farmers (id, name) VALUES ('f023', 'พี่ปุ้ย/ปลัดเพ่ง');
INSERT INTO farmers (id, name) VALUES ('f024', 'พี่ปุ้ย');
INSERT INTO farmers (id, name) VALUES ('f025', 'น้ากุ้ง1/ร้านลัคกี้');
INSERT INTO farmers (id, name) VALUES ('f026', 'พี่เขียว2/ร้านลัคกี้');
INSERT INTO farmers (id, name) VALUES ('f027', 'พี่เขียว');
INSERT INTO farmers (id, name) VALUES ('f028', 'น้ากุ้ง1/ยายแอ๋ว');
INSERT INTO farmers (id, name) VALUES ('f029', 'กาเหี้ยง');
INSERT INTO farmers (id, name) VALUES ('f030', 'พี่บ่าว ยางอ่อน 2');
INSERT INTO farmers (id, name) VALUES ('f031', 'พร');
INSERT INTO farmers (id, name) VALUES ('f032', 'ลุงเอียด');
INSERT INTO farmers (id, name) VALUES ('f033', 'แป้ง');
INSERT INTO farmers (id, name) VALUES ('f034', 'ปราศรัย');
INSERT INTO farmers (id, name) VALUES ('f035', 'พี่นุ้ย /พี่สาว');
INSERT INTO farmers (id, name) VALUES ('f036', 'แบน');
INSERT INTO farmers (id, name) VALUES ('f037', 'สาคร ลุงโยก');
INSERT INTO farmers (id, name) VALUES ('f038', 'ลุงนุ้ย');
INSERT INTO farmers (id, name) VALUES ('f039', 'ลุงนุ้ย/มอญ');
INSERT INTO farmers (id, name) VALUES ('f040', 'เชียร');
INSERT INTO farmers (id, name) VALUES ('f041', 'น้าเล็ก/น้าบุปผา1');
INSERT INTO farmers (id, name) VALUES ('f042', 'น้าภาส');
INSERT INTO farmers (id, name) VALUES ('f043', 'พ่อ 2');
INSERT INTO farmers (id, name) VALUES ('f044', 'ลุงรัตน์ 1');
INSERT INTO farmers (id, name) VALUES ('f045', 'ลุงรัตน์');
INSERT INTO farmers (id, name) VALUES ('f046', 'น้าชื่น /พี่ติ๊ก');
INSERT INTO farmers (id, name) VALUES ('f047', 'น้าชื่น /ป้าหมอน');
INSERT INTO farmers (id, name) VALUES ('f048', 'น้าชื่น');
INSERT INTO farmers (id, name) VALUES ('f049', 'พี่ตุ๊ก /น้าชื่น');
INSERT INTO farmers (id, name) VALUES ('f050', 'พี่ตุ๊ก');
INSERT INTO farmers (id, name) VALUES ('f051', 'น้าพจน์/น้าดาว');
INSERT INTO farmers (id, name) VALUES ('f052', 'น้าพจน์/น้าเยี่ยม');
INSERT INTO farmers (id, name) VALUES ('f053', 'น้าเตี้ย');
INSERT INTO farmers (id, name) VALUES ('f054', 'น้าเตี้ย 2');
INSERT INTO farmers (id, name) VALUES ('f055', 'อุษา');
INSERT INTO farmers (id, name) VALUES ('f056', 'หมอหวิน');
INSERT INTO farmers (id, name) VALUES ('f057', 'jiw 2');
INSERT INTO farmers (id, name) VALUES ('f058', 'ป้าเหมียน 1');
INSERT INTO farmers (id, name) VALUES ('f059', 'กิ๊ก/ ป้าเหวียง');
INSERT INTO farmers (id, name) VALUES ('f060', 'กิ๊ก/ ป้าหวิน1');
INSERT INTO farmers (id, name) VALUES ('f061', 'กิ๊ก/ ป้าหวิน2');
INSERT INTO farmers (id, name) VALUES ('f062', 'ป้าหวิน3');
INSERT INTO farmers (id, name) VALUES ('f063', 'ป้าหวิน2');
INSERT INTO farmers (id, name) VALUES ('f064', 'ป้าเหวียง / พี่สม');
INSERT INTO farmers (id, name) VALUES ('f065', 'ป้าเหวียง');
INSERT INTO farmers (id, name) VALUES ('f066', 'ป้าเหวียง 2');
INSERT INTO farmers (id, name) VALUES ('f067', 'น้าหลวงชุม น้าดาว');
INSERT INTO farmers (id, name) VALUES ('f068', 'ชุม');
INSERT INTO farmers (id, name) VALUES ('f069', 'น้องบ่าว');
INSERT INTO farmers (id, name) VALUES ('f070', 'ผญ.น้อย');
INSERT INTO farmers (id, name) VALUES ('f071', 'ผญ.น้อย/ออมทรัพย์');
INSERT INTO farmers (id, name) VALUES ('f072', 'ป้าคลาย');
INSERT INTO farmers (id, name) VALUES ('f073', 'น้าโต');
INSERT INTO farmers (id, name) VALUES ('f074', 'ป้าซุป/น้าโต');
INSERT INTO farmers (id, name) VALUES ('f075', 'ป้าพร/ป้าจาม');
INSERT INTO farmers (id, name) VALUES ('f076', 'ป้าพร พี่นก');
INSERT INTO farmers (id, name) VALUES ('f077', 'พี่ต้อย / ป้าสวาท');
INSERT INTO farmers (id, name) VALUES ('f078', 'อ้วน');
INSERT INTO farmers (id, name) VALUES ('f079', 'แป๊ะเอียว');
INSERT INTO farmers (id, name) VALUES ('f080', 'ลุงคง ครูแก้ว');
INSERT INTO farmers (id, name) VALUES ('f081', 'ลุงคง ครูโม๊ย');
INSERT INTO farmers (id, name) VALUES ('f082', 'ลุงคง');
INSERT INTO farmers (id, name) VALUES ('f083', 'พี่หวัง ลุงวัฒ');
INSERT INTO farmers (id, name) VALUES ('f084', 'ลุงนุ ครูสกุล');
INSERT INTO farmers (id, name) VALUES ('f085', 'ลุงนุ');
INSERT INTO farmers (id, name) VALUES ('f086', 'น้าอู๊ด');
INSERT INTO farmers (id, name) VALUES ('f087', 'น้องขิง พี่ธิดา');
INSERT INTO farmers (id, name) VALUES ('f088', 'น้องขิง ป้าหมาย');
INSERT INTO farmers (id, name) VALUES ('f089', 'พี่แหม่ม / น้ามา');
INSERT INTO farmers (id, name) VALUES ('f090', 'น้าปัท/ติ่มซัม');
INSERT INTO farmers (id, name) VALUES ('f091', 'เจ๊หลุย/พี่เอก');
INSERT INTO farmers (id, name) VALUES ('f092', 'น้าเพ็ญศรี');
INSERT INTO farmers (id, name) VALUES ('f093', 'น้าเสม/น้าเพ็ญศรี');
INSERT INTO farmers (id, name) VALUES ('f094', 'น้าเสม/น้าปู');
INSERT INTO farmers (id, name) VALUES ('f095', 'น้าเสม/ลุงวิชิต');
INSERT INTO farmers (id, name) VALUES ('f096', 'น้านุช');
INSERT INTO farmers (id, name) VALUES ('f097', 'เกี๊ยว');
INSERT INTO farmers (id, name) VALUES ('f098', 'น้าวรรณ');
INSERT INTO farmers (id, name) VALUES ('f099', 'เถ้าแก่วุฒิ /เอมม่า');
INSERT INTO farmers (id, name) VALUES ('f100', 'เป็ดน้อย พี่เสก');
INSERT INTO farmers (id, name) VALUES ('f101', 'เป็ดน้อย น้าปอง');
INSERT INTO farmers (id, name) VALUES ('f102', 'พ่อ น้าปอง');
INSERT INTO farmers (id, name) VALUES ('f103', 'น้าโพ1');
INSERT INTO farmers (id, name) VALUES ('f104', 'แอด');
INSERT INTO farmers (id, name) VALUES ('f105', 'วัล');
INSERT INTO farmers (id, name) VALUES ('f106', 'พี่ยุ้ง');
INSERT INTO farmers (id, name) VALUES ('f107', 'นาย');
INSERT INTO farmers (id, name) VALUES ('f108', 'ไผ่');
INSERT INTO farmers (id, name) VALUES ('f109', 'น้าญา');
INSERT INTO farmers (id, name) VALUES ('f110', 'น้าชิต');
INSERT INTO farmers (id, name) VALUES ('f111', 'ป้าบวน');
INSERT INTO farmers (id, name) VALUES ('f112', 'น้าตา');
INSERT INTO farmers (id, name) VALUES ('f113', 'พม่ามิงซู');
INSERT INTO farmers (id, name) VALUES ('f114', 'พม่ามิงซู 2');
INSERT INTO farmers (id, name) VALUES ('f115', 'ยางดอง');
