name = "rubertrade-co-ltd"
pages_build_output_dir = "dist"
compatibility_date = "2024-03-12"

[[d1_databases]]
binding = "DB"
database_name = "Rubertrade-Co-Ltd-db"
database_id = "5212b4bc-ec93-4fce-8949-fcaf98280c8c"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "rubertrade-co-ltd-bucket"
